### ISSUE TITLE
Building with -DADLMIDI_USE_DOSBOX_OPL doesn't exit cleanly for gen_adldata

### ISSUE THREAD

**Issue by sneakernets** [Wohlstand/libADLMIDI#17]
Tried to compile with that macro set in my c/cppflags, and no go on gen_adldata! undefined reference errors everywhere when it tries to link gen_adldata. Perhaps something to say "generate with nuked but play with dosbox" set in stone somewhere?

**Comment by Wohlstand** [comment]
That because of not built dbopl.cpp

**Comment by Wohlstand** [comment]
That because of not built dbopl.cpp. When nuked is used, dbopl.cpp is not needed to be built

**Comment by Wohlstand** [comment]
CMake now builds gen_adldata with Nuked or DosBox emulator basing on given option while configure build. I hope, this is no more an issue. CMake build is works on Windows with MinGW and MSVC, on Linux and on Mac OS X. Anyway, music player is building better on MinGW, on Linux and on macOS. 

Be careful with MSVC: gen_adldata fails to build because of some weird assert I still looking for a solution to fix it.

**Comment by Wohlstand** [comment]
Okay, GenAdldata has been fixed for MSVC build (msvc 2015+ as good support for C++11 is needed).

Please try to build stuff now and confirm a result here.
