### ISSUE TITLE
wildcard support for adlmidiplay

### ISSUE THREAD

**Issue by sneakernets** [Wohlstand/libADLMIDI#194]
I'm making a music box out of a RPi 3 for Christmas and noticed that there is no real way to play multiple files.

Here's what I get when I try a wildcard:
```
freemas@05009Freemas10:~/Code/libADLMIDI/Release$ ./adlmidiplay /mnt/c/Users/Freemas/Music/*.mid ~/Code/DMXOPL/GENMIDI\(GS\).wopl 6 6
==========================================
         libADLMIDI demo utility
==========================================

 - Library version 1.4.0
 - Nuked OPL3 (v 1.8) Emulator in use
 - Use custom bank [/mnt/c/Users/Freemas/Music/deckthe.mid]...FAILED!

ERROR: Custom bank: Invalid magic!
```

**Comment by Wohlstand** [comment]
Player itself doesn't supports playlists, however, the bash script (also for Windows can be used) that allows you to sequentially play all songs by wildcard:
```bash
#!/bin/bash
for song in /mnt/c/Users/Freemas/Music/*.mid
    # where is -nl - NoLoop, and where is -fp - Full Panning
    ./adlmidiplay "$song" -nl -fp ~/Code/DMXOPL/GENMIDI\(GS\).wopl 6 6
done
```

Anyway, the error was caused by the fact the wildcard was converted into chain of arguments that have resulted second song be treated as bank file that was caused an error.

I'll need completely change current interface of adlmidiplay utility as it sucks in the current form as now. One note it'll be incompatible to old one.

**Comment by sneakernets** [comment]
That's fine! Yeah the bash script idea will work for now. I may do that but instead of playing them in realtime I can export all the songs to WAV format using my patches and use a Music CD or something. I was noticing some popping and skipping sounds sometimes when using the Pi 3+, and ARM aren't *really* known for their single threaded performance...

And Dosbox emu messes with my cymbals and power snare way too much, booo :(

**Comment by Wohlstand** [comment]
Did you tried to use lesser chips count if Nuked? Anyway, if CPU is too weak, then yeah, making pre-recordings also a choice. You can generate OGG or OPUS with a wise choice of quality, and play that even via VLC in command line mode (VLC is able to work with no graphics)
