### ISSUE TITLE
Percussion with "1-tic notes" breaks percussion

### ISSUE THREAD

**Issue by sneakernets** [Wohlstand/libADLMIDI#23]
This really has been an issue lately - some midi racks back in the day let the composer get away with 1-tic notes without any real issues. This causes problems for libADLMIDI, however, because any percussion FM patch worth its salt never gets to finish playing its attack before the release is called, causing my snares to go "boop boop boop"

Most sequencers I've used used at least *a minimum* of 8 or 16 tics. Voyetra Sequencer defaulted to 16.

**Comment by Wohlstand** [comment]
In DOOM snares was a junk second voice that must be removed to avoid those boops. Reason of boops are notes with attack, decay, and very low "sustain". Also just having decay with low sustain. Too short note tick causes release on middle of decay. Do you mean making the workaround to force percussion note offs be farther than a limit?
Also very annoying thing that some MIDI files has percussion notes with zero length which also causes various issues with sound.

**Comment by sneakernets** [comment]
here is a test midi file with this problem on the snares. It plays on Roland SCC-1, somehow! 

[Nin_-_head_like_a_hole.zip](https://github.com/Wohlstand/libADLMIDI/files/1325701/Nin_-_head_like_a_hole.zip)

**Comment by Wohlstand** [comment]
The reason why on Roland that playing fine is explainable:
* in case of FM chip, every drum is same melodic instrument with attack, decay, and release are sensitive to note off signals. Therefore extra boops are possible on very short notes.
* in case of wavetable synthesizer, every drum is pre-recorded sample which playing completely (usually setting very far release and zero attack)

**Comment by Wohlstand** [comment]
Good news!
In the "seekability" branch I completely reworked a way to store MIDI data to make the ability to easily seek absolute seconds time position. With this I'll have easier and safer way to delay percussion note-offs when there are too near to their note-off. After I'll stabilize it, I'll try to implement this thing to finally get rid of this inconvenience!

**Comment by Wohlstand** [comment]
Now I almost completed a fix for this "hell of all ages"!
* [MIDI File](http://wohlsoft.ru/docs/_files_for_posts/Misc/AdlMidi-Percussion-HellOfAllAges/celebration.mid) 
* [Recorded fragment before the of fix](http://wohlsoft.ru/docs/_files_for_posts/Misc/AdlMidi-Percussion-HellOfAllAges/celebration.mid-before-fix.ogg)
* [Recorded fragment played on my experimental fixed player](http://wohlsoft.ru/docs/_files_for_posts/Misc/AdlMidi-Percussion-HellOfAllAges/celebration.mid-after-fix.ogg) where I moving note-offs forward away in the pre-processed MIDI data.

However, your "Head like a hole" still play short notes on bongos and sometimes on a kick drums (because of weird note-offs inside a file, I still work to beat this, then I'll commit my fix for everyone)

**Comment by Wohlstand** [comment]
As this is completed and works, so, I can close this
