### ISSUE TITLE
[WinMM Driver] The driver installation doesn't work for some reason

### ISSUE THREAD

**Issue by NotTheMindProbe** [Wohlstand/libADLMIDI#281]
There appears to be a required drvsetup.exe or something as part of the project, which install.bat refers to, and doesn't exist

**Comment by Wohlstand** [comment]
Hello! What packaed you tried to install? The `drvsetup.exe` is included in all these pacakges (on 64-bit systems, you should use the "all" package that installs both 32-bit and 64-bit versions, because if you run 32-bit apps, they do require a 32-bit driver). If it has gone, please check your antivirus' quarantine, it's a possible false positive.

**Comment by NotTheMindProbe** [comment]
How do I install a specific package? I didn't know there was a way to specify specific packages to install

**Comment by Wohlstand** [comment]
Download this: <https://builds.wohlsoft.ru/win32/libADLMIDI-winmm-driver-all.7z>, then unpack, and run "install.bat". Actually there are also separated 32-bit and 64-bit packages provided in separate archives.

**Comment by NotTheMindProbe** [comment]
It worked! Thanks!!
Do you recommend I install both x64 and x86 versions or just the x64 one? I use a 64-bit OS

**Comment by Wohlstand** [comment]
You need both on 64-bit, because if you will install 64-bit only, when you run 32-bit apps, they will see that it's no driver installed. Because it's a user-mode driver, it gets used by client applications directly like plugins.
