### ISSUE TITLE
Rework rhythm-mode percussions system

### ISSUE THREAD

**Issue by Wohlstand** [Wohlstand/libADLMIDI#57]
Current rhythm-mode percussions system is bad:
* Rhythm-mode drums in most are mapped incorrectly, there are working only in case of playing CMFs.
* No way to use WOPL's and IBK's rhythm-mode percussions

What need to do:
* Remove away `percussionMap` and store the rhythm-mode flags into the byte of flags (togeter with "no-sound" and "pseudo-4op")
* Automatize `AdLib percussions` mode when using IBK-based bank, or when WOPL contains at least one drum with a rhythm-mode type.

**Comment by Wohlstand** [comment]
Began some work on editor side:
https://github.com/Wohlstand/OPL3BankEditor/commit/58842631cac3a2a7c21df120d5156f48c95bef89
Now rythm-mode drums are finally can sound, but hi-hats and cymbals still work incorrectly.

**Comment by papiezak** [comment]
On player (VLC plugin to be exact) side, I spotted interesting behaviour of cymbal-type percussion instruments - during playback, their timbre seems to change, or they sound differently than in bank editor.
Example: https://instaud.io/3Cn7 - after crash cymbal (of normal FM percussion type) hi-hat's timbre changes a bit, sometimes difference is much more apparent. It doesn't happen on any other banks.
I used Nuked 1.8, since other emulators have problems with percussion mode.
[adlib perc.zip](https://github.com/Wohlstand/libADLMIDI/files/3132314/adlib.perc.zip) - contains recording, .mid file, wopl bank and .opli instrument.

**Comment by Wohlstand** [comment]
Oh, forgot to check this task, it's made, but, yeah, it's now "polishing"

**Comment by Wohlstand** [comment]
Damn, I forgot to notice that not working cymbals was been fixed a while ago, so, they were working.

**Comment by freq-mod** [comment]
>not working cymbals was been fixed a while ago, so, they were working.

Weird, on my side everything is still either broken or sounds incorrectly
[OPL2.zip](https://github.com/Wohlstand/libADLMIDI/files/5080205/OPL2.zip) - contains bank file, .mid sample and recording
Note the wrong sounding snare and completely missing hi-hats, cymbals also sound differently in bank editor and during song playback. Maybe it has somrthing to do with measurer bug in [OPL3BE](https://github.com/Wohlstand/OPL3BankEditor/issues/27)

**Comment by Wohlstand** [comment]
Hello!
As the main topic of this task got solved, let's report any existing rhythm-mode problems at new issues?
