### ISSUE TITLE
Dynamic bank loading does not work

### ISSUE THREAD

**Issue by jpcima** [Wohlstand/libADLMIDI#83]
I have implemented functionality in realtime MIDI software to dynamically load the bank when it detects a change on disk.
So, editing and saving the bank will act like a poor man's realtime edition of instruments.

libADLMIDI reports success in reloading the bank, but the timbres don't change! (however volumes do)

For example I go in the bank editor, and copy gunshot into acoustic grand piano.
Bank reloads with success, timbre is not changed. With program restarted and bank loaded in a fresh player, it's good.

I am doing these steps [in code](https://github.com/jpcima/adljack/blob/master/sources/common.cc#L352)

1. I acquire the player lock
2. Call `adl_panic` (same with `adl_reset`)
3. `adl_openBankFile`. gets return code >= 0

**Comment by Wohlstand** [comment]
Sees the thing I need to check out here...

**Comment by jpcima** [comment]
I have changed a ton of things in latest adlrt. I am preparing it for a 1.0 release.
It will be compatible with windows, and possibly will support MIDI virtual port on it.
But I want the banks fixed!!! :smile: If I finish with the other things, I'll give a deeper look into what might be wrong with the bank loading.

**Comment by Wohlstand** [comment]
Just for a joke:
![default](https://user-images.githubusercontent.com/6751442/39677059-9d35042a-517d-11e8-8a95-2cd2acec493f.png)
and another bank also loaded:
![default](https://user-images.githubusercontent.com/6751442/39677063-ac5fc566-517d-11e8-8525-1e2b473f2482.png)
but sounding bank is ... Wolfenstein!
So, it's a BUG, gotta to fix it NOW...

**Comment by Wohlstand** [comment]
Fixed that just now! :fox_face: :+1: 
@jpcima , feel free to check out the result :wink:

**Comment by jpcima** [comment]
Ah, very good! it's a pleasure now. Nice work.

Do you mind if the bank editor gets a Ctrl+S action to save directly, instead as saving "as". To remove some weight from the workflow of confirming saving each time.
Thanks for fixing it. :+1: 

> So, it's a BUG, gotta to fix it NOW...

Oh god... Today I was searching for hours why my Windows version in PDCurses did not display the good terminal colors. All for a stupid missing preprocessor definition which fixed everything.

**Comment by Wohlstand** [comment]
About of editor's save: I may allow quick save for some of formats because of some source bank formats are may require extra choice from a user, that for bank formats are storing percussive and melodic sets in separated files like IBK and HMI. Because of those formats is need to choose what do you want to export: percussion or melodic set.

**Comment by jpcima** [comment]
> allow quick save for some of formats

Yes only for the formats which do not require user interactions.

So you know, I have completed a TODO list for adljack 1.0.
There remains essentially to make a better windows installer, and after that I will make the software announcement.
I have a windows version with software midi port, for which I used [this driver](https://www.tobias-erichsen.de/software/virtualmidi.html). But I need a license permission to publish a binary, so I dropped this guy a mail. So it will be possible to connect the software to Dosbox and other things.

**Comment by Wohlstand** [comment]
Just now I have checked his license text and seems a license conflict:
* GPL/LGPL allows to distribute stuff anywhere with any purposes include of modifying the whole stuff except of software that linked with LGPL-ed library that may have any different license.
* His license mesns no one can distribute without his permission. This also meand modded or forked software made from off our stuff we are having.
So, as we are speaking about of source code, then we are can refer his to take his SDK to build our stuff and let everyone deal with his license independently. When we are speaking about of binary, this means even he allowed us to distribute the stuff, everyone allowed to modify the whole our stuff and re-distribute or embed the whole thing into something another big or remix everything into anything. But because of his license some limits may come which directly conflicts with GPL/LGPL...

**Comment by jpcima** [comment]
> Software linking to this SDK MAY NOT BE DISTRIBUTED

Technically I'm not linking "to the SDK". I'm linking at runtime dll if it's there, and if not I skip and continue on. So to pretend I link to SDK is a false statement. :smile:

(legal questions are so open for interpretation, than no one can pretend to have definite answers until jurisprudence)

I have constructed it this way so this driver can be used as optional component. This driver's DLL is not supposed to be shipped with programs, but to be found in a C:/Windows folder.

I know for fact that runtime linking is less contraining, when it comes to GPL/LGPL software.
When I get a mail reply of him, I can ask the author for more detail on the license issues.
